# Generated by Django 2.2 on 2021-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproductsiteparser', '0004_portabletaexistingproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportNewProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_new_products', models.IntegerField(default=0)),
                ('service_pack_new_products', models.IntegerField(default=0)),
                ('magazingsm_new_products', models.IntegerField(default=0)),
                ('portableta_new_products', models.IntegerField(default=0)),
                ('moka_gsm_new_products', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
