# Generated by Django 2.2 on 2021-07-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproductsiteparser', '0005_weeklyreportnewproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyReportNewProducts',
        ),
    ]
