# Generated by Django 2.2 on 2020-11-14 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_adminlogofjobtoshow_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='is_competitor_rule_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='is_margin_rule_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='is_original_price_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PriceCompetitorRuleReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_pricer', models.FloatField(default=0)),
                ('check_pricer_unit', models.IntegerField(default=1)),
                ('check_pricer_priority', models.IntegerField(default=1)),
                ('competitor_priority', models.IntegerField(default=1)),
                ('is_all_competitors', models.BooleanField(default=False)),
                ('final_price_check', models.FloatField(default=0)),
                ('final_price_unit', models.IntegerField(default=1)),
                ('is_all_suppliers', models.BooleanField(default=False)),
                ('is_all_categories', models.BooleanField(default=False)),
                ('is_on_product', models.BooleanField(default=False)),
                ('is_on_category', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='products.Categories')),
                ('competitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCompetitorSites')),
                ('product_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Rules')),
                ('supplier', models.ManyToManyField(to='products.Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='MarginRulesReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0)),
                ('percentage_unit', models.IntegerField(default=2)),
                ('type', models.IntegerField(default=0)),
                ('is_all_suppliers', models.BooleanField(default=False)),
                ('is_all_categories', models.BooleanField(default=False)),
                ('is_on_product', models.BooleanField(default=False)),
                ('is_on_category', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='products.Categories')),
                ('product_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Rules')),
                ('supplier', models.ManyToManyField(to='products.Suppliers')),
            ],
        ),
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='competitor_rule_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PriceCompetitorRuleReferenceModel'),
        ),
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='margin_rule_identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.MarginRulesReferenceModel'),
        ),
    ]
