# Generated by Django 2.2 on 2020-11-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201114_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginrulesreferencemodel',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='pricecompetitorrulereferencemodel',
            name='rule',
        ),
    ]
