# Generated by Django 2.2 on 2020-11-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_adminlogofjobtoshow_price_change_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='is_competitor_asscoiated',
            field=models.BooleanField(default=False),
        ),
    ]
