# Generated by Django 3.1.3 on 2020-11-22 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_adminlogofjobtoshow_is_competitor_less_than_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_page', models.BooleanField(default=False)),
                ('is_products_page', models.BooleanField(default=False)),
                ('is_rules_page', models.BooleanField(default=False)),
                ('is_competitors_page', models.BooleanField(default=False)),
                ('is_daily_price_page', models.BooleanField(default=False)),
                ('is_active_links_page', models.BooleanField(default=False)),
                ('is_cron_job_logs_page', models.BooleanField(default=False)),
                ('is_remove', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
