# Generated by Django 3.1.3 on 2020-11-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_userspermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='all_cost_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userspermissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
