# Generated by Django 2.2 on 2020-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201123_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogofjobtoshow',
            name='is_smart_price_set_applied',
            field=models.BooleanField(default=False),
        ),
    ]
