# Generated by Django 2.2 on 2021-01-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210110_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency_code',
            field=models.IntegerField(default=0),
        ),
    ]
