# Generated by Django 2.2 on 2021-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_products_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginrules',
            name='lower_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marginrules',
            name='lower_percentage_unit',
            field=models.IntegerField(default=2),
        ),
    ]
