# Generated by Django 2.2 on 2021-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_marginrules_price_dependancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='all_cost_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='local_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='margin_retail',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='margin_whole_sale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='old_all_cost_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_all_cost_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='old_retail_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_retail_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='retail_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_price_ron',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='thenx_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='whole_sale_price',
            field=models.FloatField(default=0.0),
        ),
    ]
