# Generated by Django 2.2 on 2021-01-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210118_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cheapest_comp',
            field=models.FloatField(default=0.0),
        ),
    ]
