# Generated by Django 2.2 on 2021-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_products_cheapest_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exchange_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
