# Generated by Django 2.2 on 2021-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_products_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcompetitorsitesreference',
            name='old_price_date',
            field=models.DateField(null=True),
        ),
    ]
