# Generated by Django 2.2 on 2021-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productcompetitorsitesreference_old_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='margin_retail_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='margin_whole_sale_unit',
            field=models.IntegerField(default=0),
        ),
    ]
