# Generated by Django 2.2 on 2021-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210124_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginrules',
            name='price_dependancy2',
            field=models.FloatField(default=0),
        ),
    ]
