# Generated by Django 2.2 on 2022-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_weeklyreportnewproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantJobDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.IntegerField(default=0)),
                ('product_list', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('products_price_changes', models.IntegerField(default=0)),
                ('status_of_job', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
