# Generated by Django 2.2 on 2022-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_instantjobdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantjobdeclaration',
            name='job_type',
            field=models.IntegerField(default=0),
        ),
    ]
