# Generated by Django 2.2 on 2022-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_instantjobdeclaration_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantjobdeclaration',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instantjobdeclaration',
            name='supplier',
            field=models.IntegerField(default=0),
        ),
    ]
